[workspace]
members = [
    ".",
    "ffi",
    "windows-redirector",
    "wireguard-test-client",
]

[workspace.package]
authors = [
    "Fabio Valentini <decathorpe@gmail.com>",
    "Maximilian Hils <cargo@maximilianhils.com>",
]
version = "0.2.0-beta.8"
publish = false
repository = "https://github.com/mitmproxy/mitmproxy-rs"
edition = "2021"
rust-version = "1.65.0"

[workspace.dependencies]
bincode = "2.0.0-rc.3"

[package]
name = "mitmproxy"
license = "MIT"
authors.workspace = true
version.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
log = "0.4.17"
once_cell = "1"
pretty-hex = "0.3.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }
smoltcp = "0.9"
tokio = { version = "1.23", features = ["macros", "net", "rt-multi-thread", "sync", "time", "io-util"] }
boringtun = { version = "0.5", default-features = false }
x25519-dalek = "2.0.0-pre.1"
async-trait = "0.1.60"
console-subscriber = { version = "0.1.8", optional = true }

[patch.crates-io]
# tokio = { path = "../tokio/tokio" }
tokio = { git = 'https://github.com/tokio-rs/tokio', rev = '2e7f996f17ff9cac761c775d359355d4e37555b1' }
smoltcp = { git = 'https://github.com/mhils/smoltcp', rev = 'f65351adfa92db5193f368368cb668bac721fe43' }

[target.'cfg(windows)'.dependencies]
bincode.workspace = true

[target.'cfg(windows)'.dependencies.windows]
version = "0.48.0"
features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
]

[dev-dependencies]
env_logger = "0.10"
rand = "0.8"
criterion = "0.4.0"

[[bench]]
name = "process"
harness = false

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[features]
tracing = ["console-subscriber"]
