name: autofix.ci

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  rust_clippy: 1.65  # MSRV

jobs:
  protobuf:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install swift-protobuf
      - run: protoc --swift_out=./macos-redirector/ipc --proto_path=./src/packet_sources/ ipc.proto
      - uses: autofix-ci/action@8caa572fd27b0019a65e4c695447089c8d3138b9

  rustfmt:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            args: --package windows-redirector
          - os: macos-latest
            args: --package macos-certificate-truster
          - os: ubuntu-latest
            args: --workspace --exclude windows-redirector --exclude macos-certificate-truster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-autofix-${{ hashFiles('**/Cargo.lock') }}

      - run: rustup toolchain install ${{ env.rust_clippy }} --profile minimal --component rustfmt --component clippy
      - run: rustup default ${{ env.rust_clippy }}

      - run: cargo clippy --fix --allow-dirty ${{ matrix.args }}
      - run: cargo fmt --all

      - uses: autofix-ci/action@8caa572fd27b0019a65e4c695447089c8d3138b9
