name: docs

on:
  push:
    branches:
      - main
  pull_request:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43  # v2.7.0
        timeout-minutes: 2
        continue-on-error: true
      - name: Install maturin[zig] from PyPI
        uses: install-pinned/maturin-with-zig@930de5c8284dfb26f11fd30a35a0df4c15ee4f8b
      - name: Install mypy from PyPI
        uses: install-pinned/mypy@ec0e09cd3185c17fea4006bc549fa4afa6d8a703
      - name: Install pdoc from PyPI
        uses: install-pinned/pdoc@85234c915f9aab318ed5c48a717ea15a4f46524d

      - run: maturin build
        working-directory: ./mitmproxy-rs
      - run: pip install --no-index --find-links target/wheels/ mitmproxy_rs

      - run: stubtest --allowlist mitmproxy-rs/stubtest-allowlist.txt --mypy-config-file mitmproxy-rs/pyproject.toml mitmproxy_rs

      - run: pdoc -o docs/ mitmproxy_rs

      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
